ASSETS_LIST += \
	filesystem/hydraharmonics/head-1-0.ci4.sprite \
	filesystem/hydraharmonics/head-1-1.ci4.sprite \
	filesystem/hydraharmonics/head-1-2.ci4.sprite \
	filesystem/hydraharmonics/head-1-3.ci4.sprite \
	filesystem/hydraharmonics/head-2-0.ci4.sprite \
	filesystem/hydraharmonics/head-2-1.ci4.sprite \
	filesystem/hydraharmonics/head-2-2.ci4.sprite \
	filesystem/hydraharmonics/head-2-3.ci4.sprite \
	filesystem/hydraharmonics/head-3-0.ci4.sprite \
	filesystem/hydraharmonics/head-3-1.ci4.sprite \
	filesystem/hydraharmonics/head-3-2.ci4.sprite \
	filesystem/hydraharmonics/head-3-3.ci4.sprite \
	filesystem/hydraharmonics/head-0-0.ci4.sprite \
	filesystem/hydraharmonics/head-0-1.ci4.sprite \
	filesystem/hydraharmonics/head-0-2.ci4.sprite \
	filesystem/hydraharmonics/head-0-3.ci4.sprite \
	filesystem/hydraharmonics/note-down.ci4.sprite \
	filesystem/hydraharmonics/note-neutral.ci4.sprite \
	filesystem/hydraharmonics/note-up.ci4.sprite \
